### ISSUE TITLE
Markdown component doesn't work anymore

### ISSUE THREAD

**Issue by mashehu** [astro-community/md#1]
Throws the error `(Cannot read properties of undefined (reading 'href'))`.

As pointed out on [Discord](https://discord.com/channels/830184174198718474/1071490567407665212/1071496851435552768) the following still works
```
{async() => await markdown('# Hello World')}
```

**Comment by jonathantneal** [comment]
Hi @mashehu, would you mind asking the Astro maintainers if I can access that link?

I’ll look into this today. Thank you for the report.

**Comment by mashehu** [comment]
You should be able to access the discord with this link: https://astro.build/chat

**Comment by jonathantneal** [comment]
Hi, @mashehu. Thank you again for the report.

I tried the links you shared. They are not working for me.

I suspect that I’m banned for some critical tweets that I wrote about their initial removal of Markdown support in Astro (_I believe it was before v1, and before this integration_). I have since apologized to them for those harsh tweets.

Would you mind asking them if I may be allowed back in 🙏?
I wonder if me being out of sight makes it easy to not expire their punishment.

**Comment by mashehu** [comment]
Sorry, I am not involved enough in the Astro community to know who to approach. The discord thread I linked to basically just reports the error I mention at the beginning and then someone posting the workaround with:
>Its looks like the <Markdown> component passes in a default option that breaks the rendering, so you have to use the other functions for now

**Comment by mashehu** [comment]
Yep, like a charm. Thanks a lot!
